#tomcat
server:
  port: 8080
  servlet:
    path: /
#jdbc
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day01
    username: root
    password: 123
#mybatis
mybatis:
  type-aliases-package: cn.hxzy.pojo

